- name: Deploy repository to server
  hosts: server
  vars:
    git_clone_repo: "{{ git_clone_repo }}"
    git_clone_dest: /home/devops/fokit26/Devops
    git_clone_branch: "{{ git_clone_branch }}"
  tasks:
    - name: Echo debug variables
      debug:
        msg: "repository: {{ git_clone_repo }}, branch: {{ git_clone_branch }}"
    - name: Install git
      ansible.builtin.package:
        name: git
        state: present   
    - name: Clone and checkout repository
      ansible.builtin.git:
        repo: "{{ git_clone_repo }}"
        dest: "{{ git_clone_dest }}"
        version: "{{ git_clone_branch }}"
        key_file: "/home/devops/fokit26/.ssh/gitlab-ci-exemple"
        accept_hostkey: yes
        update: yes
        force: yes