- name: Deploy repository to server
  hosts: server
  vars:
    git_clone_dest: /home/devops/fokit26/Devops
  tasks:
    - name: Include GitLab predefenition variables
      ansible.builtin.include_vars: vars_playbook.yml
    - name: Echo debag variables
      debug:
        msg: "repository: {{ git_clone_repa }}, branch: {{ git_clone_branch }}"
    - name: Install git
      ansible.builtin.package:
        name: git
        state: present   
    - name: Clone and checkout repository
      ansible.builtin.git:
        repo: "{{ git_clone_repo }}"
        dest: "{{ git_clone_dest }}"
        version: "{{ git_clone_branch }}"
        update: yes
        force: yes